[package]
name = "rust_examples"
version = "0.1.0"
edition = "2021"
rust-version = "1.62.1"

[dependencies]
csv = "1.1.6"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.9"
tempfile = "3.3"
thiserror = "1.0"
