[package]
name = "rust_examples"
version = "0.1.0"
edition = "2021"
rust-version = "1.61.0"

[dependencies]
serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.8"
tempfile = "3.3"
thiserror = "1.0"
